version: '1'
services:
  carceral-groups-api:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - mynetwork

  carceral-groups-website:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    networks:
      - mynetwork

networks:
  mynetwork: