version: '1'
services:
  carceral-groups-api:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - carceral-groups-website

  carceral-groups-website:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    command: sleep infinity
    volumes:
      - .:/workspace:cached